#!/usr/bin/env sh

sxhkd &

bspc monitor --reset-desktops
INTERNAL_MONITOR="eDP1"

xrandr --output $INTERNAL_MONITOR --auto
bspc monitor $INTERNAL_MONITOR -d 1 2 3 4 5 6

bspc config border_width 	2
bspc config window_gap 		5

bspc config split_ratio 	0.5
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true

#bspc config focus_follows_pointer true
#bspc config pointer_follows_monitor true
bspc config click_to_focus true

bspc config focused_border_color \#bbbb99
bspc config presel_border_color \#ffff00

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop=^1
bspc rule -a Code desktop=^2
bspc rule -a Slack desktop=^4
# bspc rule -a mplayer2 state=floating
# bspc rule -a Screenkey manage=off

polybar primary &
redshift &

change_wallpaper $HOME/wallpapers/interstellar.jpg

