#!/usr/bin/env bash

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:gesi/dotfiles.git"

osname=$(uname -s)

if [ -f ~/.yadm/$osname.sh ]; then
  ~/.yadm/$osname.sh
else
  echo "Bootstrap file for $osname not found"
  exit 1
fi